#!/usr/bin/env python
from verifier.verifier import verify, export_evidences
import argparse

parser = argparse.ArgumentParser("Automatically verify issues for host")
parser.add_argument("target", nargs='+', help="Target to verify the issues for")
parser.add_argument("-p", "--dradis_project_id", help="ID of dradis project")
parser.add_argument('-l', '--lang', default="en", help="Reporting language")
parser.add_argument('-x', '--export_file', help="File to export results to")
args = parser.parse_args()

evidences = []
try:
    for evidence in verify(['all'], args.target, dradis_project_id=args.dradis_project_id, lang=args.lang):
        if evidence:
            evidences.append(evidence)
finally:
    if args.export_file:
        export_evidences(evidences, args.export_file)
